In [2]:
from PIL import Image
import numpy as np
import os
import shutil
#img = Image.open('watermelon940.jpg')
#numpydata = np.asarray(img)
#print(type(numpydata))
#print(numpydata.shape)
#numpydata = numpydata.flatten()
#print(numpydata.shape)

In [6]:

from PIL import Image
import os
import numpy as np

def convert_data_to_array(folder_path, target_size=(64, 64)):
    subfolders = [f.path for f in os.scandir(folder_path) if f.is_dir()]
    data = []
    classes = []
    for i, subfolder in enumerate(subfolders):
        print(subfolder)
        subfolder_files = os.listdir(subfolder)
        for file in subfolder_files:
            full_path = os.path.join(subfolder, file)
            img = Image.open(full_path)
            # Resize the image to a fixed size
            img = img.resize(target_size)
            img_array = np.array(img)
            data.append(img_array.flatten())
            classes.append(i)
    return np.asarray(classes), np.asarray(data)

training_classes, training_data = convert_data_to_array("./train")
print(training_classes)
print(training_data)
testing_classes, testing_data = convert_data_to_array("./test")
print(testing_classes)
print(testing_data)
validation_classes, validation_data = convert_data_to_array("./val")
print(validation_classes)
print(validation_data)


./train\aloevera
./train\banana
./train\bilimbi
./train\cantaloupe
./train\cassava
[0 0 0 ... 4 4 4]
[[255 255 255 ...  25  42  23]
 [ 76 138  95 ... 231 220 152]
 [254 255 252 ... 109  74  70]
 ...
 [223 207 205 ... 255 255 255]
 [113  73  53 ...  79  59  56]
 [254 254 254 ... 254 254 254]]
./test\aloevera
./test\banana
./test\bilimbi
./test\cantaloupe
./test\cassava
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 

In [8]:
import sklearn as sk
from sklearn.svm import SVC
svm_classifier = SVC(kernel='rbf', C=100, gamma='scale', decision_function_shape='ovr')
svm_classifier.fit(training_data, training_classes)

# Evaluate classifier
accuracy = svm_classifier.score(testing_data, testing_classes)
print("Accuracy:", accuracy)